name: aesera_jewels
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0  
  image_picker: ^1.2.0
  shared_preferences: ^2.1.1
  local_auth: ^2.3.0
  url_launcher: ^6.2.6
  socket_io_client: ^3.1.2
  google_sign_in: ^6.2.1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  google_fonts: ^6.3.0
  file_picker: ^10.3.2
  connectivity_plus: ^6.1.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/AppIcon - Copy.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Lexend
  #     fonts:
  #       - asset: fonts/Lexend-Regular.ttf
  #       - asset: fonts/Lexend-Medium.ttf
  #       - asset: fonts/Lexend-Bold.ttf
          
  #   - family: Plus Jakarta Sans
  #     fonts:
  #       - asset: fonts/Plus Jakarta Sans-Medium.ttf
  #       - asset: fonts/Plus Jakarta Sans-Bold.ttf
  #       - asset: fonts/Plus Jakarta Sans-Regular.ttf
  #       - asset: fonts/Plus Jakarta Sans-semibold.ttf
  #   - family: Manrope
  #     fonts:
  #       - asset: fonts/Manrope-Medium.ttf
  #       - asset: fonts/Manrope-Bold.ttf
  #       - asset: fonts/Manrope-Regular.ttf
  #       - asset: fonts/Manrope-semibold.ttf
              
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
